hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${dataset.name}_${mode}

run:
  gen_run_id: "deterministic"
  eval_run_id: "low-temp"
  max_new_tokens: 32
mode: "dpo"

environment:
  cuda_device: "0,1"
  hf_home: path/to/hf_home
  java_home: "/home/user/java/jdk21"

wandb:
  project: RAC
  run_name: run_${mode}_${dataset.name}_${now:%Y-%m-%d}_${now:%H-%M-%S}
  disabled: false
  mode: offline


dataset:
  name: "paqa"
  fine_tune_path: "pathtotrainingdataset"
  eval_dataset: "preference_tuning_test_generated_data_paqa_0.3alpha_half_train2_fixed.json"
  dpo_dataset: evaluation_datasets/evaluation_generated_data_${dataset.name}/${run.gen_run_id}/${run.eval_run_id}/split_${dataset.train_test_split}_alpha${mixture.alpha}__lr_${model.learning_rate}schedule_${model.lr_scheduler_type}_epochs_${model.num_epochs}_beta_${dpo.beta}_loss_${dpo.loss}_lr_${dpo.learning_rate}schedule_${dpo.lr_scheduler_type}_epochs_${dpo.num_epochs}.json
  preference_dataset: dpo_datasets/preference_tuning_test_generated_data_${dataset.name}/${run.gen_run_id}/split_${dataset.train_test_split}_alpha${mixture.alpha}_lr_${model.learning_rate}schedule_${model.lr_scheduler_type}_epochs_${model.num_epochs}.json
  mixture_dataset: preference_datasets/preference_tuning_test_generated_data_paqa_0.3alpha_half_train2_fixed.json
  evaluation_dataset: evaluation_datasets/evaluation_generated_data_${dataset.name}/${run.gen_run_id}/${run.eval_run_id}/split_${dataset.train_test_split}_alpha${mixture.alpha}_beta_${dpo.beta}_loss_${dpo.loss}.json
  full_sft_eval_dataset: sft_eval_datasets/${dataset.name}/${run.eval_run_id}/split_${dataset.train_test_split}_alpha${mixture.alpha}_lr_${model.learning_rate}schedule_${model.lr_scheduler_type}_epochs_${model.num_epochs}.json
  metrics: metrics/metrics_results_${dataset.name}/${run.gen_run_id}/${run.eval_run_id}/split_${dataset.train_test_split}_alpha${mixture.alpha}model__lr_${model.learning_rate}schedule_${model.lr_scheduler_type}_epochs_${model.num_epochs}_beta_${dpo.beta}_loss_${dpo.loss}_lr_${dpo.learning_rate}schedule_${dpo.lr_scheduler_type}_epochs_${dpo.num_epochs}
  test_dataset: "passage_evidence_test_answer.json"
  llm_judge_output_path: llm_judge/${dataset.name}/${run.gen_run_id}/${run.eval_run_id}/split_${dataset.train_test_split}_alpha${mixture.alpha}model__lr_${model.learning_rate}schedule_${model.lr_scheduler_type}_epochs_${model.num_epochs}_beta_${dpo.beta}_loss_${dpo.loss}_lr_${dpo.learning_rate}schedule_${dpo.lr_scheduler_type}_epochs_${dpo.num_epochs}
  seed: 42
  train_test_split: 0.5

model:
  name: "meta-llama/Llama-3.1-8B"
  tokenizer_name: "meta-llama/Llama-3.1-8B"
  pad_token: "<|finetune_right_pad_id|>"
  chat: False
  response_template: "Clarifying Question:"
  Qlora: False
  max_seq_length: 3840
  batch_size: 2
  num_epochs: 2
  learning_rate: 1e-6
  log_level: info
  logging_steps: 10
  lr_scheduler_type: linear  
  logging_dir: "./logs"
  output_dir: checkpoint_sft_${model.name}_${dataset.name}_split_${dataset.train_test_split}_QLORA_${model.Qlora}
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  evaluation_strategy: "steps"
  save_steps: 100
  eval_steps: 100
  save_total_limit: 1
  weight_decay: 0.001
  optim: adamw_torch
  gradient_accumulation_steps: 1
  gradient_checkpointing: true
  max_grad_norm: 1.0
  seed: 12357
  warmup_ratio: 0.1
  fp16: False
  bf16: True
  load_directory: checkpoint_sft_${model.name}_${dataset.name}_split_${dataset.train_test_split}_QLORA_${model.Qlora}_lr_${model.learning_rate}_epoch_${model.num_epochs}
  uncond_save_directory: uncond_sft_${model.name}_${dataset.name}_split_${dataset.train_test_split}_lr_${model.learning_rate}_epoch_${model.num_epochs}
  save_directory: checkpoint_sft_${model.name}_${dataset.name}_split_${dataset.train_test_split}_QLORA_${model.Qlora}_lr_${model.learning_rate}_epoch_${model.num_epochs}
  dpo_directory: checkpoint_dpo_${model.name}_${dataset.name}_split_${dataset.train_test_split}_alpha${mixture.alpha}_QLORA_${model.Qlora}_lr_${model.learning_rate}_epoch_${model.num_epochs}_${dpo.beta}_loss_${dpo.loss}


dpo:
  max_seq_length: 3840
  batch_size: 2
  num_epochs: 1
  learning_rate: 1e-6
  log_level: info
  logging_steps: 1
  lr_scheduler_type: linear  
  logging_dir: "./logs"
  output_dir: checkpoint_dpo_${model.name}_${dataset.name}_split_${dataset.train_test_split}_alpha${mixture.alpha}_QLORA_${model.Qlora}_lr_${model.learning_rate}_epoch_${model.num_epochs}_${dpo.beta}_loss_${dpo.loss}
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  evaluation_strategy: "steps"
  save_steps: 100
  eval_steps: 100
  save_total_limit: 1
  optim: adamw_torch
  gradient_accumulation_steps: 1
  gradient_checkpointing: true
  max_grad_norm: 1.0
  seed: 12357
  warmup_ratio: 0.1
  fp16: False
  bf16: False
  dpo_directory: ckp_dpo_${model.name}_${dataset.name}_${run.gen_run_id}_split_${dataset.train_test_split}_alpha${mixture.alpha}_lr_${model.learning_rate}_epoch_${model.num_epochs}_${dpo.beta}_loss_${dpo.loss}
  beta: 0.1
  loss: "sigmoid"
  loss_type: "ipo"
  untouched: 6


mixture:
  alpha: 0.4
  bs: 150
  mn_bs: 150
  dpo_bs: 150
  num_variants: 1


